import React from "react";
import { styled } from "styled-components";

const StyledTable = styled.table`
  margin-bottom: 1em;
  border-spacing: 0;
  border-collapse: collapse;
  margin-right: auto;
  th,
  td {
    padding: 6px;
    border: 1px solid var(--black);
    vertical-align: top;
  }
`;

const LetterTable = styled(StyledTable)`
  td {
    width: 266px;
  }
`;

const AnswerTable = styled(StyledTable)`
  tr {
    height: 21px;
  }
  td {
    width: 120px;
  }
`;

const GreenData = styled.td`
  background-color: #b6d7a8;
`;

const GrayData = styled.td`
  background-color: #d9d9d9;
`;

const Solution = (): JSX.Element => {
  return (
    <>
      <p>
        This is a puzzle about cryptic crosswords, with the “decryption” droids
        helping to indicate how each word in a given clue functions. There is
        exactly one droid per word in the clue, but the identities of the droids
        are obscured, and solvers must figure them out as they solve individual
        clues. The complete list of droid functions can be seen here:
      </p>
      <LetterTable>
        <tr>
          <td>
            <p>A</p>
          </td>
          <td>
            <p>
              Literal: This word appears literally in the output, or it is a
              literal input to some other function.
            </p>
          </td>
        </tr>
        <tr>
          <td>
            <p>B</p>
          </td>
          <td>
            <p>
              Word hidden in clue: Indicates that an answer is hiding in plain
              sight, perhaps spanning multiple words in the clue.
            </p>
          </td>
        </tr>
        <tr>
          <td>
            <p>C</p>
          </td>
          <td>
            <p>Definition: The definition part of the clue</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>D</p>
          </td>
          <td>
            <p>
              Synonym: This word should be replaced with a synonym, whose length
              is given in parentheses.
            </p>
          </td>
        </tr>
        <tr>
          <td>
            <p>E</p>
          </td>
          <td>
            <p>
              Delete specific string: Remove some specific letter or string from
              another word.
            </p>
          </td>
        </tr>
        <tr>
          <td>
            <p>F</p>
          </td>
          <td>
            <p>
              Abbreviation: This word should be replaced by its common
              abbreviation.
            </p>
          </td>
        </tr>
        <tr>
          <td>
            <p>G</p>
          </td>
          <td>
            <p>First letter: Take the first letter of some other word.</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>H</p>
          </td>
          <td>
            <p>
              Last n letters: Take the last letter or letters of some other
              word(s)
            </p>
          </td>
        </tr>
        <tr>
          <td>
            <p>I</p>
          </td>
          <td>
            <p>
              Insert A in B: Insert what comes before this word into what comes
              after.
            </p>
          </td>
        </tr>
        <tr>
          <td>
            <p>J</p>
          </td>
          <td>
            <p>
              Even/odd letters: Take even or odd letters from a word or phrase.
            </p>
          </td>
        </tr>
        <tr>
          <td>
            <p>K</p>
          </td>
          <td>
            <p>
              Filler / linker: This word helps link the wordplay and definition.
            </p>
          </td>
        </tr>
        <tr>
          <td>
            <p>L</p>
          </td>
          <td>
            <p>
              A after B: Place the preceding string after the following string.
            </p>
          </td>
        </tr>
        <tr>
          <td>
            <p>M</p>
          </td>
          <td>
            <p>Center letter: Take the center letter of some word.</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>N</p>
          </td>
          <td>
            <p>Anagram: Anagram a word or phrase.</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>O</p>
          </td>
          <td>
            <p>Reversal: Reverse some other word or phrase.</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>P</p>
          </td>
          <td>
            <p>
              Replace letter: Replace one letter in a word with another letter.
            </p>
          </td>
        </tr>
        <tr>
          <td>
            <p>Q</p>
          </td>
          <td>
            <p>Homophone: Replace a word with a homophone.</p>
          </td>
        </tr>
      </LetterTable>
      <p>
        Droids which indicate a multi-word phrase all performing the same
        function are squashed together slightly, e.g. “housed in” which consists
        of two words both indicating “Insert A in B”.
      </p>
      <p>
        Below each set of normal clues is a single clue highlighted in gray
        whose words are all blanks. The lengths of those blanks match the
        enumerations of the preceding clues, suggesting that the answers to
        those clues need to be inserted. The inserted words, along with one more
        row of droids, produce a new cryptic crossword clue to be solved.
      </p>
      <p>
        When all of the gray boxed clues are solved, solvers may notice that
        their answer enumerations match the lengths of the blanks in the very
        last clue at the end. This final clue is a bit special: Some of the
        words are blanks, and some are just REDACTED. The droid functions are
        given as usual, and the “definition” part of the clue is simply
        “answer”.
      </p>
      <p>
        By this point solvers will need to have uncovered all of the droid
        functions. Droids such as the anagram indicator always perform the same
        operation regardless of the corresponding word in the clue, so the words
        associated with these droids are REDACTED.
      </p>
      <p>The final clue, annotated with its functions, is:</p>
      <p>
        PUNCH [synonym] ANAKIN [first letter] SKYWALKER [first letter] [insert
        into] BB DROID [center letter of] RILE [anagram] DOCK [synonym]
        [reverse] for [linker] answer [definition].
      </p>
      <p>
        A synonym of PUNCH is JAB. The first letters of ANAKIN and SKYWALKER are
        AS, so inserting them into BB gives BASB. The center letter of DROID is
        O. Anagramming RILE gives ILER. A synonym of DOCK is MOOR, which when
        reversed gives ROOM. Assembling these pieces gives JABBAS BOILER ROOM
        which is the answer.
      </p>
      <p>The complete set of regular clues, functions and answers are:</p>
      <AnswerTable>
        <tr>
          <GreenData>
            <p>Cannibalism acknowledged secret buffet</p>
          </GreenData>
          <GreenData>
            <p>Literal</p>
          </GreenData>
          <GreenData>
            <p>Literal</p>
          </GreenData>
          <GreenData>
            <p>Word hidden in clue</p>
          </GreenData>
          <GreenData>
            <p>Definition</p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p>SMACK</p>
          </GreenData>
        </tr>
        <tr>
          <GreenData>
            <p>Universal dropping Southern comedian</p>
          </GreenData>
          <GreenData>
            <p>Synonym [cosmic]</p>
          </GreenData>
          <GreenData>
            <p>Delete specific string</p>
          </GreenData>
          <GreenData>
            <p>Abbreviation</p>
          </GreenData>
          <GreenData>
            <p>Definition</p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p>COMIC</p>
          </GreenData>
        </tr>
        <tr>
          <GreenData>
            <p>Hedberg might initially irritate</p>
          </GreenData>
          <GreenData>
            <p>Definition</p>
          </GreenData>
          <GreenData>
            <p>Literal</p>
          </GreenData>
          <GreenData>
            <p>First letter</p>
          </GreenData>
          <GreenData>
            <p>Synonym [itch]</p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p>MITCH</p>
          </GreenData>
        </tr>
        <tr>
          <GreenData>
            <p>Marijuana butts eaten by horse eventually</p>
          </GreenData>
          <GreenData>
            <p>Literal</p>
          </GreenData>
          <GreenData>
            <p>Last N letters</p>
          </GreenData>
          <GreenData>
            <p>Insert A in B</p>
          </GreenData>
          <GreenData>
            <p>ditto</p>
          </GreenData>
          <GreenData>
            <p>Synonym [filly]</p>
          </GreenData>
          <GreenData>
            <p>Definition</p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p>FINALLY</p>
          </GreenData>
        </tr>
        <tr>
          <GreenData>
            <p>Following closer to the stern</p>
          </GreenData>
          <GreenData>
            <p>Definition</p>
          </GreenData>
          <GreenData>
            <p>Definition</p>
          </GreenData>
          <GreenData>
            <p>ditto</p>
          </GreenData>
          <GreenData>
            <p>ditto</p>
          </GreenData>
          <GreenData>
            <p>ditto</p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p>AFTER</p>
          </GreenData>
        </tr>
        <tr>
          <GreenData>
            <p>Even DJ Rookie is a fool</p>
          </GreenData>
          <GreenData>
            <p>Even/Odd letters</p>
          </GreenData>
          <GreenData>
            <p>Literal</p>
          </GreenData>
          <GreenData>
            <p>ditto</p>
          </GreenData>
          <GreenData>
            <p>Filler</p>
          </GreenData>
          <GreenData>
            <p>ditto</p>
          </GreenData>
          <GreenData>
            <p>Definition</p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p>JOKE</p>
          </GreenData>
        </tr>
        <tr>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
        </tr>
        <tr>
          <GreenData>
            <p>Warrior housed in Anjediva</p>
          </GreenData>
          <GreenData>
            <p>Definition</p>
          </GreenData>
          <GreenData>
            <p>Word hidden in clue</p>
          </GreenData>
          <GreenData>
            <p>ditto</p>
          </GreenData>
          <GreenData>
            <p>Literal</p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p>JEDI</p>
          </GreenData>
        </tr>
        <tr>
          <GreenData>
            <p>Survives using core samples primarily</p>
          </GreenData>
          <GreenData>
            <p>Definition</p>
          </GreenData>
          <GreenData>
            <p>Literal</p>
          </GreenData>
          <GreenData>
            <p>Center letter</p>
          </GreenData>
          <GreenData>
            <p>Literal</p>
          </GreenData>
          <GreenData>
            <p>First letter</p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p>IS</p>
          </GreenData>
        </tr>
        <tr>
          <GreenData>
            <p>One peach pit</p>
          </GreenData>
          <GreenData>
            <p>Definition</p>
          </GreenData>
          <GreenData>
            <p>Literal</p>
          </GreenData>
          <GreenData>
            <p>Center letter</p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p>A</p>
          </GreenData>
        </tr>
        <tr>
          <GreenData>
            <p>Impotent authority, even elders, heart of issue</p>
          </GreenData>
          <GreenData>
            <p>Definition</p>
          </GreenData>
          <GreenData>
            <p>Synonym [power]</p>
          </GreenData>
          <GreenData>
            <p>Even/Odd letters</p>
          </GreenData>
          <GreenData>
            <p>Literal</p>
          </GreenData>
          <GreenData>
            <p>Center letter</p>
          </GreenData>
          <GreenData>
            <p>ditto</p>
          </GreenData>
          <GreenData>
            <p>Literal</p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p>POWERLESS</p>
          </GreenData>
        </tr>
        <tr>
          <GreenData>
            <p>Break family cloth</p>
          </GreenData>
          <GreenData>
            <p>Synonym [nap]</p>
          </GreenData>
          <GreenData>
            <p>Synonym [kin]</p>
          </GreenData>
          <GreenData>
            <p>Definition</p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p>NAPKIN</p>
          </GreenData>
        </tr>
        <tr>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
        </tr>
        <tr>
          <GreenData>
            <p>Vacuum mangled capes</p>
          </GreenData>
          <GreenData>
            <p>Definition</p>
          </GreenData>
          <GreenData>
            <p>Anagram</p>
          </GreenData>
          <GreenData>
            <p>Literal</p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p>SPACE</p>
          </GreenData>
        </tr>
        <tr>
          <GreenData>
            <p>Drunken revel follows returning art tourist</p>
          </GreenData>
          <GreenData>
            <p>Anagram</p>
          </GreenData>
          <GreenData>
            <p>Literal</p>
          </GreenData>
          <GreenData>
            <p>A after B</p>
          </GreenData>
          <GreenData>
            <p>Reversal</p>
          </GreenData>
          <GreenData>
            <p>Literal</p>
          </GreenData>
          <GreenData>
            <p>Definition</p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p>TRAVELER</p>
          </GreenData>
        </tr>
        <tr>
          <GreenData>
            <p>Apostle gag changed profit to loss</p>
          </GreenData>
          <GreenData>
            <p>Definition</p>
          </GreenData>
          <GreenData>
            <p>Synonym [puke]</p>
          </GreenData>
          <GreenData>
            <p>Replace letter</p>
          </GreenData>
          <GreenData>
            <p>Abbreviation</p>
          </GreenData>
          <GreenData>
            <p>Filler</p>
          </GreenData>
          <GreenData>
            <p>Abbreviation</p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p>LUKE</p>
          </GreenData>
        </tr>
        <tr>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
        </tr>
        <tr>
          <GreenData>
            <p>Cry audibly for reception</p>
          </GreenData>
          <GreenData>
            <p>Synonym [bawl]</p>
          </GreenData>
          <GreenData>
            <p>Homophone</p>
          </GreenData>
          <GreenData>
            <p>Filler</p>
          </GreenData>
          <GreenData>
            <p>Definition</p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p>BALL</p>
          </GreenData>
        </tr>
        <tr>
          <GreenData>
            <p>Not opposed to hiding in Scarif orbit</p>
          </GreenData>
          <GreenData>
            <p>Definition</p>
          </GreenData>
          <GreenData>
            <p>ditto</p>
          </GreenData>
          <GreenData>
            <p>ditto</p>
          </GreenData>
          <GreenData>
            <p>Word hidden in clue</p>
          </GreenData>
          <GreenData>
            <p>ditto</p>
          </GreenData>
          <GreenData>
            <p>Literal</p>
          </GreenData>
          <GreenData>
            <p>ditto</p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p>FOR</p>
          </GreenData>
        </tr>
        <tr>
          <GreenData>
            <p>Show us involved in absurd claim</p>
          </GreenData>
          <GreenData>
            <p>Definition</p>
          </GreenData>
          <GreenData>
            <p>Literal</p>
          </GreenData>
          <GreenData>
            <p>Insert A in B</p>
          </GreenData>
          <GreenData>
            <p>ditto</p>
          </GreenData>
          <GreenData>
            <p>Anagram</p>
          </GreenData>
          <GreenData>
            <p>Literal</p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p>MUSICAL</p>
          </GreenData>
        </tr>
        <tr>
          <GreenData>
            <p>Royal band turning somber ending into knight’s debut</p>
          </GreenData>
          <GreenData>
            <p>Definition</p>
          </GreenData>
          <GreenData>
            <p>Synonym [ring]</p>
          </GreenData>
          <GreenData>
            <p>Replace letter</p>
          </GreenData>
          <GreenData>
            <p>Literal</p>
          </GreenData>
          <GreenData>
            <p>Last N letters</p>
          </GreenData>
          <GreenData>
            <p>Filler</p>
          </GreenData>
          <GreenData>
            <p>Literal</p>
          </GreenData>
          <GreenData>
            <p>First letter</p>
          </GreenData>
          <GreenData>
            <p>KING</p>
          </GreenData>
        </tr>
        <tr>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
        </tr>
        <tr>
          <GreenData>
            <p>Odd roomba reverting to machine</p>
          </GreenData>
          <GreenData>
            <p>Even/Odd letters</p>
          </GreenData>
          <GreenData>
            <p>Literal</p>
          </GreenData>
          <GreenData>
            <p>Reversal</p>
          </GreenData>
          <GreenData>
            <p>Literal</p>
          </GreenData>
          <GreenData>
            <p>Definition</p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p>ROBOT</p>
          </GreenData>
        </tr>
        <tr>
          <GreenData>
            <p>Messed up escape, hemorrhaged</p>
          </GreenData>
          <GreenData>
            <p>Definition</p>
          </GreenData>
          <GreenData>
            <p>ditto</p>
          </GreenData>
          <GreenData>
            <p>Synonym [scram]</p>
          </GreenData>
          <GreenData>
            <p>Synonym [bled]</p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p>SCRAMBLED</p>
          </GreenData>
        </tr>
        <tr>
          <GreenData>
            <p>Wireless radiator leaks messy tar</p>
          </GreenData>
          <GreenData>
            <p>Definition</p>
          </GreenData>
          <GreenData>
            <p>Literal</p>
          </GreenData>
          <GreenData>
            <p>Delete specific string</p>
          </GreenData>
          <GreenData>
            <p>Anagram</p>
          </GreenData>
          <GreenData>
            <p>Literal</p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p>RADIO</p>
          </GreenData>
        </tr>
        <tr>
          <GreenData>
            <p>Drop of wine enters exhausting trading</p>
          </GreenData>
          <GreenData>
            <p>First letter</p>
          </GreenData>
          <GreenData>
            <p>ditto</p>
          </GreenData>
          <GreenData>
            <p>Literal</p>
          </GreenData>
          <GreenData>
            <p>Insert A in B</p>
          </GreenData>
          <GreenData>
            <p>Synonym [sapping]</p>
          </GreenData>
          <GreenData>
            <p>Definition</p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p>SWAPPING</p>
          </GreenData>
        </tr>
        <tr>
          <GreenData>
            <p>Match goal an upset</p>
          </GreenData>
          <GreenData>
            <p>Definition</p>
          </GreenData>
          <GreenData>
            <p>Literal</p>
          </GreenData>
          <GreenData>
            <p>Literal</p>
          </GreenData>
          <GreenData>
            <p>Anagram</p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p>ANALOG</p>
          </GreenData>
        </tr>
        <tr>
          <GreenData>
            <p>Warning misheard in support</p>
          </GreenData>
          <GreenData>
            <p>Synonym [fore]</p>
          </GreenData>
          <GreenData>
            <p>Homophone</p>
          </GreenData>
          <GreenData>
            <p>Definition</p>
          </GreenData>
          <GreenData>
            <p>ditto</p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p>FOR</p>
          </GreenData>
        </tr>
        <tr>
          <GreenData>
            <p>Ass in face online</p>
          </GreenData>
          <GreenData>
            <p>Synonym [git]</p>
          </GreenData>
          <GreenData>
            <p>Insert A in B</p>
          </GreenData>
          <GreenData>
            <p>Synonym [dial]</p>
          </GreenData>
          <GreenData>
            <p>Definition</p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p>DIGITAL</p>
          </GreenData>
        </tr>
        <tr>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
        </tr>
        <tr>
          <GreenData>
            <p>Rattle in Audi’s turbocharger</p>
          </GreenData>
          <GreenData>
            <p>Definition</p>
          </GreenData>
          <GreenData>
            <p>Word hidden in clue</p>
          </GreenData>
          <GreenData>
            <p>Literal</p>
          </GreenData>
          <GreenData>
            <p>Literal</p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p>DISTURB</p>
          </GreenData>
        </tr>
        <tr>
          <GreenData>
            <p>Paddle back without wife either</p>
          </GreenData>
          <GreenData>
            <p>Synonym [row]</p>
          </GreenData>
          <GreenData>
            <p>Reversal</p>
          </GreenData>
          <GreenData>
            <p>Delete specific string</p>
          </GreenData>
          <GreenData>
            <p>Abbreviation</p>
          </GreenData>
          <GreenData>
            <p>Definition</p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p>OR</p>
          </GreenData>
        </tr>
        <tr>
          <GreenData>
            <p>Finish queasy after dark ending</p>
          </GreenData>
          <GreenData>
            <p>Definition</p>
          </GreenData>
          <GreenData>
            <p>Synonym [ill]</p>
          </GreenData>
          <GreenData>
            <p>A after B</p>
          </GreenData>
          <GreenData>
            <p>Literal</p>
          </GreenData>
          <GreenData>
            <p>Last N letters</p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p>KILL</p>
          </GreenData>
        </tr>
        <tr>
          <GreenData>
            <p>Note sung for myself</p>
          </GreenData>
          <GreenData>
            <p>Synonym [mi]</p>
          </GreenData>
          <GreenData>
            <p>Homophone</p>
          </GreenData>
          <GreenData>
            <p>Filler</p>
          </GreenData>
          <GreenData>
            <p>Definition</p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p>ME</p>
          </GreenData>
        </tr>
        <tr>
          <GreenData>
            <p>Evelyn collapses regularly</p>
          </GreenData>
          <GreenData>
            <p>Literal</p>
          </GreenData>
          <GreenData>
            <p>Anagram</p>
          </GreenData>
          <GreenData>
            <p>Definition</p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p>EVENLY</p>
          </GreenData>
        </tr>
        <tr>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
        </tr>
        <tr>
          <GreenData>
            <p>Researcher is after recalled cod</p>
          </GreenData>
          <GreenData>
            <p>Definition</p>
          </GreenData>
          <GreenData>
            <p>Filler</p>
          </GreenData>
          <GreenData>
            <p>Synonym [post]</p>
          </GreenData>
          <GreenData>
            <p>Reversal</p>
          </GreenData>
          <GreenData>
            <p>Literal</p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p>POSTDOC</p>
          </GreenData>
        </tr>
        <tr>
          <GreenData>
            <p>P.S.: Following retrospective yelp continues</p>
          </GreenData>
          <GreenData>
            <p>Literal</p>
          </GreenData>
          <GreenData>
            <p>A after B</p>
          </GreenData>
          <GreenData>
            <p>Reversal</p>
          </GreenData>
          <GreenData>
            <p>Synonym [eek]</p>
          </GreenData>
          <GreenData>
            <p>Definition</p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p>KEEPS</p>
          </GreenData>
        </tr>
        <tr>
          <GreenData>
            <p>Secret toll follows greeting</p>
          </GreenData>
          <GreenData>
            <p>Definition</p>
          </GreenData>
          <GreenData>
            <p>Synonym [hi]</p>
          </GreenData>
          <GreenData>
            <p>A after B</p>
          </GreenData>
          <GreenData>
            <p>Synonym [ding]</p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p>HIDING</p>
          </GreenData>
        </tr>
        <tr>
          <GreenData>
            <p>Silly Lisp error</p>
          </GreenData>
          <GreenData>
            <p>Anagram</p>
          </GreenData>
          <GreenData>
            <p>Literal</p>
          </GreenData>
          <GreenData>
            <p>Definition</p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p></p>
          </GreenData>
          <GreenData>
            <p>SLIP</p>
          </GreenData>
        </tr>
      </AnswerTable>
      <p>The gray boxed clues, functions, and answers are:</p>
      <AnswerTable>
        <tr>
          <GreenData>
            <p>SMACK</p>
          </GreenData>
          <GreenData>
            <p>Definition</p>
          </GreenData>
          <td>
            <p>PUNCH</p>
          </td>
        </tr>
        <tr>
          <GreenData>
            <p>COMIC</p>
          </GreenData>
          <GreenData>
            <p>Literal</p>
          </GreenData>
          <td>
            <p></p>
          </td>
        </tr>
        <tr>
          <GreenData>
            <p>MITCH</p>
          </GreenData>
          <GreenData>
            <p>Literal</p>
          </GreenData>
          <td>
            <p></p>
          </td>
        </tr>
        <tr>
          <GreenData>
            <p>FINALLY</p>
          </GreenData>
          <GreenData>
            <p>Last N letters</p>
          </GreenData>
          <td>
            <p></p>
          </td>
        </tr>
        <tr>
          <GreenData>
            <p>AFTER</p>
          </GreenData>
          <GreenData>
            <p>A after B</p>
          </GreenData>
          <td>
            <p></p>
          </td>
        </tr>
        <tr>
          <GreenData>
            <p>JOKE</p>
          </GreenData>
          <GreenData>
            <p>Synonym [pun]</p>
          </GreenData>
          <td>
            <p></p>
          </td>
        </tr>
        <tr>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
        </tr>
        <tr>
          <GreenData>
            <p>JEDI</p>
          </GreenData>
          <GreenData>
            <p>Definition</p>
          </GreenData>
          <td>
            <p>ANAKIN</p>
          </td>
        </tr>
        <tr>
          <GreenData>
            <p>IS</p>
          </GreenData>
          <GreenData>
            <p>Filler</p>
          </GreenData>
          <td>
            <p></p>
          </td>
        </tr>
        <tr>
          <GreenData>
            <p>A</p>
          </GreenData>
          <GreenData>
            <p>Literal</p>
          </GreenData>
          <td>
            <p></p>
          </td>
        </tr>
        <tr>
          <GreenData>
            <p>POWERLESS</p>
          </GreenData>
          <GreenData>
            <p>Delete specific string</p>
          </GreenData>
          <td>
            <p></p>
          </td>
        </tr>
        <tr>
          <GreenData>
            <p>NAPKIN</p>
          </GreenData>
          <GreenData>
            <p>Literal</p>
          </GreenData>
          <td>
            <p></p>
          </td>
        </tr>
        <tr>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
        </tr>
        <tr>
          <GreenData>
            <p>SPACE</p>
          </GreenData>
          <GreenData>
            <p>Synonym [sky]</p>
          </GreenData>
          <td>
            <p>SKYWALKER</p>
          </td>
        </tr>
        <tr>
          <GreenData>
            <p>TRAVELER</p>
          </GreenData>
          <GreenData>
            <p>Synonym [walker]</p>
          </GreenData>
          <td>
            <p></p>
          </td>
        </tr>
        <tr>
          <GreenData>
            <p>LUKE</p>
          </GreenData>
          <GreenData>
            <p>Definition</p>
          </GreenData>
          <td>
            <p></p>
          </td>
        </tr>
        <tr>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
        </tr>
        <tr>
          <GreenData>
            <p>BALL</p>
          </GreenData>
          <GreenData>
            <p>Definition</p>
          </GreenData>
          <td>
            <p>BB</p>
          </td>
        </tr>
        <tr>
          <GreenData>
            <p>FOR</p>
          </GreenData>
          <GreenData>
            <p>Filler</p>
          </GreenData>
          <td>
            <p></p>
          </td>
        </tr>
        <tr>
          <GreenData>
            <p>MUSICAL</p>
          </GreenData>
          <GreenData>
            <p>Definition</p>
          </GreenData>
          <td>
            <p></p>
          </td>
        </tr>
        <tr>
          <GreenData>
            <p>KING</p>
          </GreenData>
          <GreenData>
            <p>ditto</p>
          </GreenData>
          <td>
            <p></p>
          </td>
        </tr>
        <tr>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
        </tr>
        <tr>
          <GreenData>
            <p>ROBOT</p>
          </GreenData>
          <GreenData>
            <p>Definition</p>
          </GreenData>
          <td>
            <p>DROID</p>
          </td>
        </tr>
        <tr>
          <GreenData>
            <p>SCRAMBLED</p>
          </GreenData>
          <GreenData>
            <p>Anagram</p>
          </GreenData>
          <td>
            <p></p>
          </td>
        </tr>
        <tr>
          <GreenData>
            <p>RADIO</p>
          </GreenData>
          <GreenData>
            <p>Literal</p>
          </GreenData>
          <td>
            <p></p>
          </td>
        </tr>
        <tr>
          <GreenData>
            <p>SWAPPING</p>
          </GreenData>
          <GreenData>
            <p>Replace letter</p>
          </GreenData>
          <td>
            <p></p>
          </td>
        </tr>
        <tr>
          <GreenData>
            <p>ANALOG</p>
          </GreenData>
          <GreenData>
            <p>Abbreviation</p>
          </GreenData>
          <td>
            <p></p>
          </td>
        </tr>
        <tr>
          <GreenData>
            <p>FOR</p>
          </GreenData>
          <GreenData>
            <p>Filler</p>
          </GreenData>
          <td>
            <p></p>
          </td>
        </tr>
        <tr>
          <GreenData>
            <p>DIGITAL</p>
          </GreenData>
          <GreenData>
            <p>Abbreviation</p>
          </GreenData>
          <td>
            <p></p>
          </td>
        </tr>
        <tr>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
        </tr>
        <tr>
          <GreenData>
            <p>DISTURB</p>
          </GreenData>
          <GreenData>
            <p>Definition</p>
          </GreenData>
          <td>
            <p>RILE</p>
          </td>
        </tr>
        <tr>
          <GreenData>
            <p>OR</p>
          </GreenData>
          <GreenData>
            <p>Literal</p>
          </GreenData>
          <td>
            <p></p>
          </td>
        </tr>
        <tr>
          <GreenData>
            <p>KILL</p>
          </GreenData>
          <GreenData>
            <p>ditto</p>
          </GreenData>
          <td>
            <p></p>
          </td>
        </tr>
        <tr>
          <GreenData>
            <p>ME</p>
          </GreenData>
          <GreenData>
            <p>ditto</p>
          </GreenData>
          <td>
            <p></p>
          </td>
        </tr>
        <tr>
          <GreenData>
            <p>EVENLY</p>
          </GreenData>
          <GreenData>
            <p>Even/Odd letters</p>
          </GreenData>
          <td>
            <p></p>
          </td>
        </tr>
        <tr>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
          <GrayData>
            <p></p>
          </GrayData>
        </tr>
        <tr>
          <GreenData>
            <p>POSTDOC</p>
          </GreenData>
          <GreenData>
            <p>Literal</p>
          </GreenData>
          <td>
            <p>DOCK</p>
          </td>
        </tr>
        <tr>
          <GreenData>
            <p>KEEPS</p>
          </GreenData>
          <GreenData>
            <p>ditto</p>
          </GreenData>
          <td>
            <p></p>
          </td>
        </tr>
        <tr>
          <GreenData>
            <p>HIDING</p>
          </GreenData>
          <GreenData>
            <p>Word hidden in clue</p>
          </GreenData>
          <td>
            <p></p>
          </td>
        </tr>
        <tr>
          <GreenData>
            <p>SLIP</p>
          </GreenData>
          <GreenData>
            <p>Definition</p>
          </GreenData>
          <td>
            <p></p>
          </td>
        </tr>
      </AnswerTable>
    </>
  );
};

export default Solution;
