version: 2
updates:
  - package-ecosystem: "npm"
    directory: "site"
    schedule:
      interval: "weekly"
      day: "friday"
    open-pull-requests-limit: 20
    groups:
      tsrest:
        patterns:
          - "@ts-rest/*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
