site:
    environment: ENC[AES256_GCM,data:UF5ZzuVxf4a64jxDD1z98djEppZBz3yfmBpLvK/5U2/qyUXc30z3JFzZ5BSFLov9xrmU12OYa72XvZ/4p1sLlf4MecRQg188lxyyb8+XSEnsfHrPs4GaC7VjDCnM6R1VeZHTbP70jk0R9Itp/iYHYOZy6+fuAXsR5Kv/80SZEiOxuCOLrtEknsycCFLQaeWNxxuz247xPNGYLlv7K/INP9iHKOLmVDdhHtciNgpo+Hwm64rWz/x7S+c7DhYX03X5SyHy4fyj1F0iV5OCD95agsntUuBArlTpmwlIvKre3CVIP3OQytoAw6nln0isVD5HvDKD8UjRNz5sZktrW+4+LWWu29qMCa1a5g3z6gzi/diy/howy8YXtrzyWQHfqZkGJPOYMG2W6POsNyCgepnBw8+y8V+2ZMTmIcHTvt367I7lQeIkvAVxM3TV9pzt7q+0EFE4CTISqHxExVfygX3RXcVpKRIAqGNaK3rLzOpgHvLljrWw3cDpXWAcDcSq+8/q8G7/SejLPiDvAzdxQ5yj/O7aLqLaHhV0Zw+BohPmloZqiQVCu5HDFCo/eE53mLRTkuLjOQd/njQdDd75gtzX3ptBgSx66Pd09FJQCZwfYpZijqNVgk3nLkjvaM82FXvi2yAG1XW81AHOtOv5JzY085pvigX1Q5IVPQerjQNbNQ==,iv:Sz/8nroTdzBnx0EeTMd2CBp1DSRBQ7VzB0YAgpWXPsQ=,tag:WEKZY1OlBhVpq+Yv+VD1JA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/mitmh2025-staging-gcp/locations/global/keyRings/sops/cryptoKeys/sops-dev-key
          created_at: "2025-01-07T21:26:28Z"
          enc: CiQAgd8qXLBuF3DIyra+kOiPcgv9ovZsskY+sCHaP0Vg2A3FDWYSSQAVikAVTAXuO0u1zS0ZUIXn1hls/5M2LpSsqFp/aiDB/uqpmZeGh+b9hzXNiqT11KEcW4H5fWE48xtDyTRf3OQdKF/VIfT+rLQ=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-01-10T01:19:06Z"
    mac: ENC[AES256_GCM,data:LtV78RkYMNfiAZtgCV1W/307JGy9jn/haCNuYEjuiGUj/Ab86k7lf4uVNqHg9Huq+AgZe+AhvkZry9oa/GjFdkKvNUzWIEeGaATMGKcDMeR1y+qJqeYL71/mEP51QJi8FKMh+tZsjuKe6NrmswadwyfC36fB0gPxvr88LAkB/jI=,iv:XVjIZTVnJfiuGl9hU4HgY7ENXMXmK6ha1L/ICanTvSo=,tag:WhXqmm8fVnkMb7IfV7SWdg==,type:str]
    pgp:
        - created_at: "2025-01-07T21:26:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQQOA0yM37R1hzq+EA/+OSEjnZiXzZOagmhoc1p/llYDsa/aFeXnYVYofqWO2UJo
            axEOkNfyU6pUiIFLVmEpGrqQa8PZ+czSIMK5tF+Y515a/b9hXtohOLvQxkReDym2
            lnE28lwcPtMciQnRJXjpID4/F20C+bEuj5ULk4iP9/SePNhpm9Dq5rbiop4kRs6U
            qLbXWfdYXkP3sWQIeharfbhdahUCRJGS8vkzzMIRS2nZml2XV2cLqF97IBpuYTln
            4WMHVfO9F5X8XguvVYa1o4AYPignzKcWx/Jva+4KWxkC2W4Sv3y483x4o9DLO0KR
            6jE/ym1CsfcxCsVxd7Fx2fHfXpkCdjktRRh2G9WlrkMwzXsQDDmcXKGYR8INVtiY
            wyb7achmq1AANuCCk/G3VFjmJiXbdrem61QDKfjNGpNne/rzAuEl1MgasdVQdyP0
            cA8kMNmbW7MFswpTNy+hIrtLbBBC0K2yHOdoEK9sLgaPNgKehJa+LmbrbdkQui5S
            tfbhd/rRQQ+29jv92NjxaM0a22lnBm6Cq08Kma/JdK2PGsuJe4WTfK69YMVz3PrM
            USXjtwp/k+j0GMhe3DUOKM3iCxulBV9GcZqMMbVkX88N2JRRbIeLX12SCMeei64t
            aAleEWfPaMwyjUNV6GU2zDI4kcvwLqA1HT1FIF7z3DLrTOVA0KPfanJ+efFffS0P
            /1NVkruAa5s8UT/qkE6NPu3A1dBU/z5iecoP/NNrvqN3OWryD3yCtIC+gwjfGI6P
            i7abyOvYpiX7KZOKpkE4gf2xSf/dwQsqMJpJASFspqyTkrf4IHWomeVrLWoCNsBs
            P5XMPUKDSuqdplOPAgn0uSa4vjLqyJ0JvzM9L8/na6a3pDwFKpK37NMAA7WYSHtV
            KuLFJfA8pQvrmbNxpPnX/kJOszA8383Yx3WtWClOjNRwGMLP61Vu6jqoFP/bGprq
            qftE5E/fVhOJOrk966A9uSGzm7q6eJLTqyGniVWyUnKiMmOvjvHUtAG2V4kLFLHL
            tqD2T/aSZcH5aRs+oJDEVBJfJ/674S20BRobmg2pFQkXmsmXqUpn8h9Qy1RtFR9D
            AS2nFjgbV8z0oFNYfpXoefelJ06yG+BZctUtXeir8LUnd7/+O41OJ3zktuITdOma
            mgiizrKG1l4JCKdTiwYculevdQnoGFqEH/cwUlwBwpI19CL9xQ1COkaUhJtYIgP7
            651IIjnOvLSkHfHrFtD5Lk/dO/FzjIKbG6taX8vjgbb92mm+FhTVaCxeVTo3armD
            BT3HVvsKWuY3TdEysN9+LqiUg2E9WuVb109km8kP0HRj+fEz6Hsyh/iPY+ukMMqj
            CoMD2a0ZOYfKUCVny6N+be0mK9FhzhSGzDKzz41F9diW0l4B5ZtLudAgbXsxtw/l
            miCW1JfBTYyecO4S1KD+uZyeRL+g3WCGPtVoI6apjSLzw4JUPwE6KelU3S8sxCy4
            TYskqRZLp821/F+Jsqm6hagE2dURqI8wfPmoDw5UTEYf
            =Ef4y
            -----END PGP MESSAGE-----
          fp: 1C71A0665400AACD142EB1A004EE05A8FCEFB697
    unencrypted_suffix: _unencrypted
    version: 3.9.2
