keys:
- &admin_quentin_gpg 1C71A0665400AACD142EB1A004EE05A8FCEFB697
creation_rules:
- path_regex: secrets/staging\.yaml$
  key_groups:
  - pgp:
    - *admin_quentin_gpg
    gcp_kms:
    - resource_id: projects/mitmh2025-staging-gcp/locations/global/keyRings/sops/cryptoKeys/sops-staging-key
- path_regex: secrets/prod/deploy\.yaml$
  key_groups:
  - pgp:
    - *admin_quentin_gpg
    gcp_kms:
    - resource_id: projects/mitmh2025/locations/global/keyRings/sops/cryptoKeys/sops-deploy-key
- path_regex: secrets/prod/media\.yaml$
  key_groups:
  - pgp:
    - *admin_quentin_gpg
    gcp_kms:
    - resource_id: projects/mitmh2025/locations/global/keyRings/sops/cryptoKeys/sops-media-key
- path_regex: secrets/prod/things\.yaml$
  key_groups:
  - pgp:
    - *admin_quentin_gpg
    gcp_kms:
    - resource_id: projects/mitmh2025-staging-gcp/locations/global/keyRings/sops/cryptoKeys/sops-staging-key
    - resource_id: projects/mitmh2025/locations/global/keyRings/sops/cryptoKeys/sops-things-key
- path_regex: secrets/prod/site\.yaml$
  key_groups:
  - pgp:
    - *admin_quentin_gpg
    gcp_kms:
    - resource_id: projects/mitmh2025/locations/global/keyRings/sops/cryptoKeys/sops-site-key
