keys:
- &admin_quentin_gpg 1C71A0665400AACD142EB1A004EE05A8FCEFB697
creation_rules:
- path_regex: secrets/staging\.yaml$
  key_groups:
  - pgp:
    - *admin_quentin_gpg
    gcp_kms:
    - resource_id: projects/mitmh2025-staging-gcp/locations/global/keyRings/sops/cryptoKeys/sops-staging-key
