const TEAM_NAMES = [
  { username: "TFETeam", name: "TaskforceEarth" },
  { username: "simhunt", name: "Wafflehaüs" },
  { username: "team3734", name: "Team 3734" },
  { username: "highfive", name: "HighFive" },
  { username: "palindrome", name: "Palindrome" },
  { username: "AmateurHour", name: "Amateur Hour" },
  { username: "lexingtons", name: "The Lexingtons" },
  { username: "teammate", name: "teammate" },
  { username: "iloveiloveegg", name: "iloveiloveegg" },
  { username: "notaplanet", name: "I'm not a planet either" },
  { username: "dootdoot", name: "dootdoot" },
  { username: "fishterious", name: "Fishterious Mysterfishies" },
  { username: "frumious", name: "Frumious Bandersnatch" },
  { username: "venividiwiki", name: "Flock of Wiki Worms" },
  { username: "hunches", name: "Hunches in Bunches" },
  { username: "tableflip", name: "tableflip" },
  { username: "omnomnomnom", name: "Om Nom Nom Nom" },
  { username: "singles", name: "Singles Ready to Stay Inside" },
  { username: "ladderdogs", name: "ladderdogs" },
  { username: "societyofspirits", name: "Society of Enigmatic Spirits" },
  { username: "llamas", name: "Small Llama Malls" },
  { username: "nes", name: "NES" },
  { username: "TinkersHollow", name: "Tinkers' Hollow" },
  { username: "17thshard", name: "17th Shard" },
  { username: "etphoneinanswer", name: "ET Phone in Answer" },
  { username: "titleofteam", name: "[title of team]" },
  { username: "richiebear", name: "Richie Bear" },
  { username: "brownie", name: "Ultimate Brownies" },
  { username: "QDecrypters", name: "Quarantine Decrypters" },
  { username: "Cyfur", name: "Cyfur@China" },
  { username: "onsearch", name: "On Search" },
  { username: "offinthelab", name: "Off in the Lab" },
  { username: "needle", name: "Space Needle in a Haystack" },
  { username: "Gditz", name: "Arcane Puzzlers 🧩" },
  { username: "manateem", name: "ManateeM" },
  { username: "belmonsters", name: "Belmonsters" },
  { username: "SleipnirsWranglers", name: "Sleipnir's Wranglers" },
  { username: "occam", name: "Occam's Depilatory Gel" },
  { username: "digamma", name: "2 MINUTES FIGHTERS" },
  { username: "Miao", name: "喵喵喵" },
  { username: "davidteam", name: "davidteam" },
  { username: "AriadnesBadgerz", name: "Ariadne's Badgerz🧶" },
  { username: "libracomplexity", name: "Libra Complexity" },
  { username: "gaulois", name: "Les Gaulois" },
  { username: "controlgroup", name: "Control Group" },
  { username: "trendsetters", name: "✈﻿✈﻿✈ Galactic Trendsetters ✈﻿✈﻿✈" },
  { username: "puzzkill", name: "Puzzkill" },
  { username: "stumped", name: "Stumped and Furious" },
  { username: "sporegiant", name: "Spore Giant" },
  { username: "TheGr88Ones", name: "The Gr88 Ones" },
  { username: "SetecAstrology", name: "Setec Astrology" },
  { username: "jeffsmohan", name: "geniucez" },
  { username: "werewolves", name: "☃" },
  { username: "tetacetera", name: "Tetacetera" },
  { username: "ue", name: "⛎ UNICODE EQUIVALENCE" },
  { username: "love", name: "Grand Unified Theory of Love" },
  { username: "Donut", name: "The Donut Inside the Donut" },
  { username: "Test Solution Bees Ignore", name: "Test Solution Bees Ignore" },
  { username: "cardinality", name: "Cardinality" },
  { username: "foreverywy", name: "APTOZG" },
  { username: "gradunifiedtheory", name: "Grad Unified Theory" },
  { username: "laf", name: "Literally Animal Farm" },
  { username: "acorn.peasants", name: "Acorn Peasants" },
  { username: "vantablack2024", name: "Vantablack" },
  { username: "TheMathemagicians", name: "Math and Vehem" },
  { username: "FYS", name: "APTOZG" },
  { username: "Sabotages", name: "Sabotages" },
  { username: "Segatobas", name: "Segatobas" },
  { username: "superteamawesome", name: "Super Team Awesome" },
  { username: "plane-tix-25", name: "Plane Tickets are Expensive" },
  { username: "cservices", name: "Central Services" },
  { username: "setec", name: "Setec Astronomy" },
  { username: "EggDumpling", name: "Egg Dumpling" },
  { username: "Mango", name: "Mango the Doggo" },
  { username: "management", name: "Ange Management" },
  { username: "ussens", name: "inmemoryof" },
  { username: "windowsvista", name: "windowsvista" },
  { username: "pond", name: "ℙoNDeterministic" },
  { username: "newhouse", name: "New House Mystery Hunters" },
  { username: "one-puzzle-wonder", name: "One Puzzle Wonder" },
  { username: "seepsusan", name: "seep susan" },
  { username: "bahinterlopers", name: "BAH Interlopers" },
  { username: "mostintelligenttigers", name: "Most Intelligent banandicuTes" },
  { username: "furious.acorns", name: "Furious Acorns" },
  { username: "ducksoup", name: "Duck Soup" },
  { username: "plaidthong", name: "Plaid Thong" },
  { username: "giphy4eva", name: "An Attempt Was Made" },
  { username: "waltkidney", name: "Providence Crime Syndication" },
  { username: "showerpomelo", name: "Shower Pomelo 🍈" },
  { username: "LostInABagOfWhiteRice", name: "(required)" },
  { username: "lardcakes", name: "Lard Cakes" },
  { username: "smung", name: "Smung Institute" },
  { username: "sufficientlylargen", name: "Sufficiently Large N" },
  { username: "purple-hays", name: "Purple Hays" },
  { username: "picturegame", name: "Eradication & Chaos @ r/PictureGame" },
  { username: "Kaibai", name: "=。=" },
  { username: "raingang", name: "Rain Gang" },
  {
    username: "untilmoraleimproves",
    name: "Sorting By Every Column Until Morale Improves",
  },
  { username: "SirDooth", name: "Traffic Jam Control" },
  { username: "rage", name: "All the World's a Rage" },
  { username: "OTP", name: "The Moment I Knew" },
  {
    username: "friendsandstuff",
    name: "PERSON NAME OVERWATCH PLAYER COLORFUL DESCRIPTOR ENDEARING MONIKER DUBIOUS ACCOMPLISHMENT ONLINE HANDLE ANIME GIRL #1 FAN + friends",
  },
  { username: "rtchunt", name: "Relatively Theoretical Constructs" },
  { username: "anagalacticscoobygang", name: "Anagalactic Scooby Gang" },
  { username: "uplate", name: "Up Late" },
  { username: "NowNamed", name: "The Team That Is Now Named Later" },
  { username: "leftout", name: "Left Out" },
  { username: "unseen", name: "Team Unseen" },
  { username: "wetrieddontcriticize", name: "wetrieddontcriticize" },
  { username: "dumbnbased", name: "Dumb 'n' Based" },
  { username: "plant", name: "Metaphysical Plant" },
  { username: "yuzzlehunters", name: "Y₀" },
  { username: "French Fries", name: "French Fries" },
  { username: "BlackDynamite25", name: "Black Dynamite" },
  { username: "jarthur", name: "Random Puzzle Order" },
  { username: "Codex", name: "Codex Calixtinus" },
  { username: "vaguely", name: "Vaguely Eloquent Team" },
  { username: "donnerhunt", name: "Donner Party" },
  { username: "spicypecans", name: "Spicy Pecans" },
  { username: "could", name: "it could be fun" },
  {
    username: "ttbnl",
    name: "The Team Formerly Known as the Team Formerly Known as the Team Formerly Known as the Team Formerly Known as the Team Formerly Known as the Team Formerly Known as The Team To Be Named Later",
  },
  { username: "MozeOso", name: "The Hive Rind" },
  { username: "webbmama", name: "Webbz" },
  { username: "CaptainDinosaur", name: "Corvus Ailurus Mus" },
  { username: "ornamental_salt", name: "Linguine Amigo" },
  { username: "puzzlywuzzlies", name: "The Puzzly Wuzzlies!" },
  { username: "emoji", name: "🦦🪷🪺" },
  { username: "chiloquin", name: "Chiloquin's Heroes" },
  { username: "iif", name: "Immoral, Illegal & Fattening" },
  { username: "skn", name: "we should come up with something smart" },
  { username: "black-sheep", name: "baa baa black sheep" },
  { username: "kwargers", name: "kwargers" },
  { username: "themcraballyzeros", name: "Them Crab Ally Zeros" },
  { username: "ec2e", name: "beasties" },
  { username: "eugenia12346", name: "eggs in a carton" },
  { username: "RTNP", name: "Real Thieves Nabbing Paintings" },
  { username: "NamIridum", name: "Nam Iridum 🌈" },
  { username: "m404", name: "M404 Not Found" },
  { username: "22s", name: "22s" },
  { username: "21K", name: "21K" },
  {
    username: "doorsplease",
    name: "Team This Is An Uptown Local 1 Train For: Van Cortlandt Park - 242nd Street. This Train Is Going Express. The Next Stop Is: 137th Street - City College. Stand Clear Of The Closing Doors, Please",
  },
  { username: "sisterraucous", name: "Raucous Raucous Rhinos" },
  { username: "tmack", name: 'Our Team Name is "Team Name"' },
  { username: "[stimulant] [animal]", name: "[stimulant] [animal]" },
  { username: "Antipodium", name: "Antipodium🇦🇺" },
  { username: "Geese", name: "Pan Galactic Goose Syndicate" },
  { username: "AlwaysRainy", name: "Always Rainy" },
  { username: "Anaxciot", name: "Crystal Maiden" },
  { username: "vibhar", name: "Chillidawgs" },
  { username: "teamsnow", name: "Good Will Puzzlehunting" },
  { username: "intermittentpuzzlers", name: "The Infinite Puzzlemasters" },
  { username: "teamgeo", name: "Team Geo" },
  { username: "lowkeyneon", name: "team chips for now" },
  { username: "Udajoat", name: "Joat" },
  { username: "teamUnknown", name: "Team Unknown" },
  { username: "buildersguild", name: "Builders' Guild" },
  { username: "beangirls", name: "beangirls" },
  { username: "AstroPals", name: "AstroPals" },
  { username: "allaboutthemeta", name: "All About the Meta" },
  { username: "platonicliquids", name: "Platonic Liquids" },
  { username: "sloop", name: "Sloopertroop" },
  { username: "orz", name: "Galactic Puzzle Hunters 2024" },
  { username: "Too Kly Kly", name: "TooKlyKly" },
  { username: "andrewdrewl", name: "pp" },
  { username: "Nope", name: "Nope" },
  { username: "puzzledome", name: "The Puzzledome" },
  { username: "Luigi", name: "Luigi's Death Stare" },
  {
    username: "TheOneFromScarboroughFair",
    name: "The One From Scarborough Fair",
  },
  { username: "antimonia", name: "La Reina de los Rompecabezas 🧩👸🧩" },
  { username: "stringcheesetheory", name: "String Cheese Theory" },
  { username: "MisterDaly", name: "WASH YOUR HANDS" },
  { username: "CPTAS", name: "Colorado Pub Trivia All-Stars" },
  { username: "bang", name: "!" },
  { username: "vexedandperplexed", name: "Vexed and Perplexed" },
  { username: "Nutboys", name: "Nutboys" },
  { username: "wols", name: "wols" },
  { username: "puzzfeed", name: "Bridal Cats" },
  { username: "Bagel", name: "Bagel" },
  { username: "arausche", name: '"jupgrade"' },
  { username: "JAKS", name: "JAKS" },
  { username: "StriketeamA", name: "DoongulgeDoongulge(Clap)" },
  { username: "quizquiztofferson", name: "Quiz Quiztofferson" },
  { username: "Dirty Martinis", name: "Dirty Martinis" },
  { username: "candc", name: "Cricket and Crosswords" },
  { username: "Azoth", name: "The Azoth Consortium" },
  { username: "QuizzyDan", name: "Detectives Amidst Nuptials" },
  { username: "mangotango", name: "Mango" },
  { username: "joker", name: "🃏" },
  {
    username: "Puzzle_and_Key_Universe",
    name: "Masterminds of Ingenious Thefts",
  },
  { username: "mortalwombats", name: "Mortal Wombats" },
  { username: "rumswizzlers", name: "The Rum Swizzlers" },
  { username: "Cheatahs", name: "Cheatahs" },
  { username: "CA", name: "Team Constructed Adventures" },
  { username: "kevinlee", name: "Fuzzy Befuddled Family Puzzlers" },
  { username: "meowmeow", name: "meowmeow" },
  { username: "interoves", name: "inter oves locum praesta" },
  { username: "happybirthdayjimin", name: "happybirthdayjimin" },
  {
    username: "ucsbccs",
    name: "We Tried Getting Domino's Delivered To Storkë Tower And It Worked",
  },
  { username: "Bob", name: "Elsbels" },
  { username: "catcrabfish", name: "The Cat, The Crab and The Fish" },
  { username: "carleillinois", name: "The Laundromat @ Carle" },
  { username: "OrbPonderers", name: "Orb Ponderers" },
  { username: "spacity", name: "Midnight Marauders" },
  { username: "Mill Girl", name: "Mill Girls (+Guys)" },
  { username: "thndrmatt", name: "Maxwell Rose" },
  { username: "Crossheir", name: "Maxwell's angel" },
  { username: "ThePtrocanfers", name: "The Ptrocanfers" },
  { username: "Pennys", name: "Pennys" },
  { username: "Cruciverbalists", name: "Cruciverbalists" },
  { username: "anewtspen", name: "Enpe🦢t" },
  { username: "xfoldersteam", name: "X-Folders Team" },
  { username: "dnm-1", name: "D&M Test 1" },
  { username: "dnm-2", name: "D&M Test 2" },
  { username: "dnm-3", name: "D&M Test 3" },
  { username: "dnm-4", name: "D&M Test 4" },
  { username: "dnm-5", name: "D&M Test 5" },
  { username: "19077frb", name: "NUIST tour" },
  { username: "birdgang", name: "bird gang" },
  { username: "puzzlelambdaphuzzle", name: "puzzlelambdaphuzzle" },
  { username: "cookedandclueless", name: "Cooked and Clueless" },
  { username: "treville", name: "Monsieur de Tréville and The Musketeers" },
  { username: "therearefourlights", name: "There Are Four Lights" },
  { username: "Flamingo Bellagio", name: "Flamingo Bellagio" },
  { username: "MyTeamFINAL-FINAL", name: "My Team (2) (edited)" },

  // seed teams for testing
  { username: "team", name: "Default Team" },
  { username: "unlocked", name: "Unlocked Team" },
  {
    username: "solved",
    name: "Solved Team with a 🦢 very long 🦢 and weird name that just goes on and on and on and just goes on and on and on and just goes on and on and on and",
  },
];

const TEAM_NAMES_BY_USERNAME = TEAM_NAMES.reduce<Record<string, string>>(
  (acc, team) => {
    acc[team.username] = team.name;
    return acc;
  },
  {},
);

export function getTeamName(username: string): string {
  return TEAM_NAMES_BY_USERNAME[username] ?? username;
}
