import React, { type ReactNode } from "react";
import Blanks from "../../components/Blanks";
import { AuthorsNote } from "../../components/PuzzleLayout";

const LYRICS: ReactNode[][] = [
  [
    "What you show, baby I spot it",
    "How I look, well I know you’ve got it",
    "",
    "All I’m askin’ is for a little ████ in my bedroom",
    "(Just a little bit) Hey baby",
    "(Just a little bit) in my bedroom",
    "(Just a little bit) mister",
    "(Just a little bit)",
    "",
    "I ain’t gonna break you up, on the wall",
    "Seven years bad luck, know I don’t wanna",
    "",
    "All I’m askin’ is for a little ████ in my bedroom",
    "(Just a little bit) baby",
    "(Just a little bit) in my bedroom",
    "(Just a little bit) Yeah",
    "(Just a little bit)",
    "",
    "I’m about to put on all of my make-up",
    "And all I’m askin’, ain’t no big shake-up",
    "Is to show me my picture in my bedroom",
    "",
    "(Just a, just a, just a, just a) Yeah, baby",
    "(Just a, just a, just a, just a) In my bedroom",
    "(Just a little bit) Yeah",
    "(Just a little bit)",
    "",
    "Ooh, your shine, bright as a star now",
    "And guess what? So is my hair now",
    "",
    "All I want you to do for me, is show it to me in my bedroom",
    "(█, █, █, █) Yeah baby",
    "(█, █, █, █) Show it to me",
    "(████, just a little bit) In my bedroom, now",
    "(Just a little bit)",
    "",
    "█-█-⑥-④-█-█-█, send that image back to me",
    "█-█-⑥-④-█-█-█, this visage that I see",
    "",
    "(Show it to me, show it to me, show it to me, show it to me)",
    "A little ████",
    "(Show it to me, show it to me, show it to me, show it to me)",
    "Whoa, babe",
    "(Just a little bit) A little ████",
    "(Just a little bit) I look tired?",
    "(Just a little bit) Keep on tryin’",
    "(Just a little bit) Ain’t runnin’ out of looks",
    "(Just a little bit) And I ain’t lyin’",
    "(Just a little bit)",
    "(█, █, █, █) Start when I come home",
    "(█, █, █, ████) Or I might walk in",
    "(Just a little bit) And decide you’re gone",
    "(Just a little bit) I gotta have",
    "(Just a little bit) A little ████",
    "(Just a little bit)",
  ],
  [
    "Five, six",
    "Five, six, seven, eight",
    "",
    "You just made a keg of your new creation ",
    "Untappd’s going wild for this taste sensation",
    "Gonna make a name among all craft brewers",
    "Your ale is so good, there’s been buyout rumors",
    "",
    "But how will they know it’s not sweet? (Na-na-na-na, na)",
    "A bitter, complex brew for thee (na-na-na-na, na)",
    "It ain’t no macro lager or shandy (na-na-na-na, na)",
    "You should label correctly, label correctly (na-na-na-na, na)",
    "",
    "█-█-②-⑤-█-█-█",
    "Pop the cap and have a go",
    "Raise a glass, now make a toast",
    "Show off what came out the oast",
    "█-█-②-⑤-█-█-█",
    "Pop the cap and have a go",
    "Raise a glass, now make a toast",
    "█-█-②-⑤-█-█-█",
    "",
    "█-█-②-⑤-█-█-█",
    "Give your beer a ██ ███",
    "█-█-②-⑤-█-█-█",
    "Give your beer a ██ ███",
    "",
    "Well, now you’ve got a beer that’s real complicated",
    "Rich and nuanced taste leaves them captivated",
    "How can you show off your great new flavor?",
    "Put a label on that will curry favor",
    "",
    "But how will they know it’s not sweet? (Na-na-na-na, na)",
    "A bitter, complex brew for thee (na-na-na-na, na)",
    "It ain’t no macro lager or shandy (na-na-na-na, na)",
    "You should label correctly, label correctly (na-na-na-na, na)",
    "",
    "█-█-②-⑤-█-█-█",
    "Pop the cap and have a go",
    "Raise a glass, now make a toast",
    "Show off what came out the oast",
    "█-█-②-⑤-█-█-█",
    "Pop the cap and have a go",
    "Raise a glass, now make a toast",
    "█-█-②-⑤-█-█-█",
    "",
    "█-█-②-⑤-█-█-█",
    "Give your beer a ██ ███",
    "█-█-②-⑤-█-█-█",
    "Give your beer a ██ ███",
    "",
    "What’s it take to sell a six-pack?",
    "What’s it take to bring one home?",
    "Hurry up, last call’s a-comin’",
    "This one’s got a ██ ███",
    "What’s it take to sell a six-pack?",
    "Hurry up, it’s nice and cold",
    "Hurry up, last call’s a-comin’",
    "This one’s got a ██ ███",
    "",
    "█-█-②-⑤-█-█-█",
    "Give your beer a ██ ███ (oh, yeah)",
    "█-█-②-⑤-█-█-█",
    "Give your beer a ██ ███ (██ ███)",
    "█-█-②-⑤-█-█-█",
    "Give your beer a ██ ███ (oh, yeah)",
    "█-█-②-⑤-█-█-█",
    "Give your beer a ██ ███",
    "",
    "Whew, it’s hot today",
    "Is anyone else hot?",
    "I kinda just want to have something simple",
    "Okay, yeah",
    "I’ll have a Pabst		",
  ],
  [
    "Where is the engine bay? It’s always hard to find",
    "What are you doing there? The engines aren’t aligned",
    "Why’d I not see you in the hall? How are you in this room?",
    "Back to the caf I go, I’ll hit the button soon",
    "",
    "I saw you venting, darling, I’m suspecting, █.⑨.█.",
    "Are you behaving, are you marinating? █.⑨.█.",
    "Now you’re gone, how is it that the crew have not won",
    "We were wrong, do your tasks ’fore the imposter’s done",
    "",
    "You seemed so far away, now you are standing near",
    "You make me feel alive, but someone died I fear",
    "I really tried to finish out, my task list’s almost through",
    "And now we’re down to three, it must be one of you",
    "",
    "I saw you venting, darling, I’m suspecting, █.⑨.█.",
    "Are you behaving, are you marinating? █.⑨.█.",
    "Now you’re gone, how is it that the crew have not won",
    "We were wrong, do your tasks ’fore the imposter’s done",
    "",
    "I saw you venting, darling, I’m suspecting, █.⑨.█.",
    "Are you behaving, are you marinating? █.⑨.█.",
    "Now you’re gone, how is it that the crew have not won",
    "We were wrong, do your tasks ’fore the imposter’s done",
    "",
    "Now you’re gone, how is it that the crew have not won",
    "We were wrong, do your tasks ’fore the imposter’s done		",
  ],
  [
    "█ is one line in the upper left",
    "█ is two lines in this panel next",
    "① is adding two more as the bottom-left’s score",
    "⑩ is writing two but one is down and now that makes you",
    "",
    "███ is all that I can see in dreams",
    "███ is haunting me in every meme",
    "Who’d’ve thought that this would have the legs to last so long and",
    "███ was made for me and you",
    "",
    "█ is one line in the upper left",
    "█ is two lines in this panel next",
    "① is adding two more as the bottom-left’s score",
    "⑩ is writing two but one is down and now that makes you",
    "",
    "███ is all that I can see in dreams",
    "███ is haunting me in every meme",
    "Who’d’ve thought that this would have the legs to last so long and",
    "███ was made for me and you",
    "",
    "███ a-was made for me and you",
    "███ a-was made for me and you		",
  ],
  [
    "Oi! Oi! Oi! Oi! Oi! Oi!",
    "Oi! Oi! Oi! Oi! Oi! Oi!",
    "Oi! Oi! Oi!",
    "",
    "See me poke out of your sandal",
    "As you walk around your place",
    "Lots of things to stub me on",
    "Got that big open space",
    "",
    "Piggies to the left of me",
    "And piggies to the right",
    "Ain’t goin’ market, ain’t got roast beef",
    "Keep your foot in sight",
    "",
    "’Cause I’m █-⑦-③",
    "I hit things well",
    "█-⑦-③",
    "And I’ll hurt like hell",
    "█-⑦-③",
    "Hope that I don’t sprain",
    "█-⑦-③",
    "Put you in pain",
    "",
    "I’m dirty, mean, I’m mighty unclean",
    "You should wash me more",
    "Public enemy, one of ten",
    "Get the score?",
    "",
    "So cover your footstools",
    "Cover your chairs",
    "Cover your tables",
    "Or you’ll get despair",
    "You watch your step at home",
    "So don’t you break my bone",
    "",
    "’Cause I’m █-⑦-③",
    "I hit things well",
    "█-⑦-③",
    "And I’ll hurt like hell",
    "█-⑦-③",
    "Hope that I don’t sprain",
    "█-⑦-③",
    "Put you in pain",
    "",
    "█-⑦-③ (Oi! Oi! Oi!)",
    "█-⑦-③ (Oi! Oi! Oi!)",
    "█-⑦-③ (Oi! Oi! Oi!)",
    "█-⑦-③ (Oi! Oi! Oi!)",
    "",
    "█-⑦-③ (Oi! Oi! Oi!)",
    "I hit things well",
    "█-⑦-③ (Oi! Oi! Oi!)",
    "And I’ll hurt like hell",
    "█-⑦-③ (Oi! Oi! Oi!)",
    "Hope that I don’t sprain",
    "█-⑦-③ (Oi! Oi! Oi!)",
    "Put you in pain		",
  ],
  [
    "It’s not about winning, it’s about ███!",
    <i key="line-1">What’s that?</i>,
    "███ is when you– ███ is– It’s like– It’s kind of– Sort of like a– ",
    "What is ███? I–",
    "Let me spell it for you.",
    "",
    "⑧ is for raising up your cardio",
    "█ is for you and me",
    "█ is for anywhere and anytime at all",
    "Out here with my ███ buddy",
    "",
    <i key="line-2">⑧ is for records I smash and shatter</i>,
    <i key="line-3">█ is for unbeatable splits</i>,
    <i key="line-4">█ is for no water breaks</i>,
    <i key="line-5">When you–</i>,
    "",
    "Hey now! Those things aren’t what ███ is all about!",
    "Now, do it like this.",
    "⑧ is for raising up your car–",
    <i key="line-6">Never! That’s completely idiotic.</i>,
    "Here, let me help you.",
    "",
    "⑧ is for raising up your cardio",
    "█ is for you and me (Try it!)",
    <i key="line-7">█ is for anywhere and anytime at all</i>,
    <i key="line-8">Out here with my ███ buddy</i>,
    "",
    <i key="line-9">
      Wait, I don’t understand this. I feel all tingly inside. Should we stop?
    </i>,
    "No, that’s how you’re supposed to be!",
    <i key="line-10">Well, I like it, let’s do it again!</i>,
    "Okay!",
    "",
    "⑧ is for romping through the countryside",
    "█ is for upright trav’ling",
    "█ is for no-fretting, fastest laps and pace setting",
    "Here with my ███ buddy",
    "",
    "Ha, ha, ha, ha, ha",
    "Ha, ha, ha, ha, ha",
    "Ha, ha, ha, ha, ha",
    "Ha, ha, ha, ha, ha",
    "Ha, ha, ha, ha, ha",
    "Ha, ha, ha, ha, ha		",
  ],
];

const Puzzle = (): JSX.Element => {
  return (
    <>
      <AuthorsNote>
        This puzzle was written and tested but held in reserve in case we needed
        to make a last-minute swap. As such, it has a placeholder answer and
        will not grant you a key for solving.
      </AuthorsNote>
      <p className="puzzle-flavor">
        I think this lyrics site might be a knockoff.
      </p>
      <hr />
      {LYRICS.map((lines, i) => (
        <React.Fragment key={i}>
          <p>
            {lines.map((line, j) => (
              <React.Fragment key={j}>
                {line}
                <br />
              </React.Fragment>
            ))}
          </p>
          <hr />
        </React.Fragment>
      ))}
      <Blanks
        structure={"_____ ___ __".split("")}
        fill={[..."12345 678 9".split(""), "10"]}
        fillPosition="below"
        fillCopyPosition="below"
      />
    </>
  );
};

export default Puzzle;
