export const UpClues: [number: number, clue: string, answer: string][] = [
  [16, "La ___ de Puerto Rico in W20", "SALA"],
  [17, "Widely used currency", "EURO"],
  [18, "Add’l game material", "DLC"],
  [19, "Hairstyle you might pick out", "AFRO"],
  [20, "And others", "ETAL"],
  [21, "Hebrew day", "YOM"],
  [22, "Cheese variety", "EDAM"],
  [23, "IRS 1040 calculation", "AGI"],
  [24, "London has a giant one on the Thames", "EYE"],
  [25, "Famous Carrie role", "LEIA"],
  [28, "Russian autocrat", "TSAR"],
  [29, "Wrap", "SHAWL"],
  [30, "Veranda", "TERRACE"],
  [31, "Met performances", "OPERAS"],
  [32, "Linkin Park album or wrestling move", "METEORA"],
  [34, "See 61", "INN"],
  [35, "Computer scientist Lovelace", "ADA"],
  [36, "Italian thing", "COSA"],
  [37, "A test for 6", "BAR"],
  [38, "Motor vehicle", "CAR"],
  [40, "See 38 (in the other list)", "TEA"],
  [41, "Type of scout", "CUB"],
  [42, "Police team", "SWAT"],
  [51, "Stride", "GAIT"],
  [52, "Hallucinogen", "LSD"],
  [53, "Wedding words", "IDO"],
  [54, "Ashes container", "URN"],
  [55, "Dune’s Duncan", "IDAHO"],
  [56, "Leer at", "OGLE"],
  [57, "Consumed", "ATE"],
  [58, "Those who give", "DONORS"],
  [59, "Monk’s hood", "COWL"],
  [60, "Wine valley", "NAPA"],
  [61, "With 34, motel chain", "DAYS"],
  [62, "Cream companion", "PEACHES"],
  [63, "Small band", "TRIO"],
  [64, "Turkish leader", "ERDOGAN"],
  [65, "Apple voice", "SIRI"],
];

export const DownRightClues: [number: number, clue: string, answer: string][] =
  [
    [1, "“It’s ___ nothing”", "ALLOR"],
    [2, "Qatari monarch", "EMIR"],
    [3, "Paris suburb with an airport", "ORLY"],
    [4, "High card", "ACE"],
    [5, "Scull", "OAR"],
    [6, "One who tries?", "LAWYER"],
    [7, "Lock up", "CAGE"],
    [8, "Novelist Grafton", "SUE"],
    [9, "Took the bus", "RODE"],
    [10, "Org. that certifies gold", "RIAA"],
    [11, "___ glance", "ATA"],
    [12, "GI ration", "MRE"],
    [13, "Change", "ADAPT"],
    [14, "Health insurer", "AETNA"],
    [15, "Admit, with “up”", "FESS"],
    [16, "Very, in Vienna", "SEHR"],
    [19, "Some voices", "ALTOS"],
    [26, "Hydrocarbon suffix", "ENE"],
    [27, "Core muscles", "ABS"],
    [29, "Common prefix in California", "SAN"],
    [30, "Mathematician Terence", "TAO"],
    [31, "Hall partner", "OATES"],
    [32, "Where you might be solving this puzzle", "MIT"],
    [33, "Owed", "DUE"],
    [35, "Sneeze noise", "ACHOO"],
    [36, "Large gathering", "CROWD"],
    [37, "Japanese toy company", "BANDAI"],
    [38, "Spiced variety of 40", "CHAI"],
    [39, "Like a coyote, perhaps", "WILY"],
    [42, "Sprawling tale", "SAGA"],
    [43, "Letter starter", "DEAR"],
    [44, "Smell", "ODOR"],
    [45, "Costello or Reed", "LOU"],
    [46, "Beams", "GRINS"],
    [47, "Fourth mo.", "APR"],
    [48, "Editor’s mark", "STET"],
    [49, "Frequent Final Fantasy name", "CID"],
    [50, "French city overrepresented in punny crossword clues", "NICE"],
    [51, "Deity", "GOD"],
    [52, "Once around a track", "LAP"],
  ];
