export type FermitQuestion = {
  id: number;
  text: string;
  answer: number;
  geoguessr: number | null;
  scoringMethod: string;
  categories: string[];
};

export const ALL_QUESTIONS: FermitQuestion[] = [
  {
    id: 0,
    text: "How many smoots will take you from one end of the Infinite Corridor to the other?",
    answer: 147.4,
    geoguessr: null,
    scoringMethod: "percent",
    categories: ["distance"],
  },
  {
    id: 1,
    text: "Where is this location on campus?",
    answer: 0,
    geoguessr: 1,
    scoringMethod: "raw",
    categories: [],
  },
  {
    id: 2,
    text: "In what year did the Mystery Hunt first exceed 100 non-meta puzzles?",
    answer: 2003,
    geoguessr: null,
    scoringMethod: "12345",
    categories: ["hunt_history"],
  },
  {
    id: 3,
    text: "How many gender-inclusive bathrooms are there in the Main Group? (That’s buildings 1, 3, 5, 7, 2, 4, 6, 8, 6C, 10, and 11.)",
    answer: 15,
    geoguessr: null,
    scoringMethod: "12468",
    categories: ["bathrooms"],
  },
  {
    id: 4,
    text: "In building 2, there’s a sculpture called Chord. How many cylindrical rods are in that sculpture?",
    answer: 905,
    geoguessr: null,
    scoringMethod: "percent",
    categories: ["art"],
  },
  {
    id: 5,
    text: "Where is this location on campus?",
    answer: 0,
    geoguessr: 2,
    scoringMethod: "raw",
    categories: [],
  },
  {
    id: 6,
    text: "If MIT tuition increased by the same percentage as it did from 2014 to 2024, what will one semester of tuition cost in 2034?",
    answer: 42964.67,
    geoguessr: null,
    scoringMethod: "percent",
    categories: [],
  },
  {
    id: 7,
    text: "How many teams are signed up for this Mystery Hunt?",
    answer: 145,
    geoguessr: null,
    scoringMethod: "3double",
    categories: ["hunt_current"],
  },
  {
    id: 8,
    text: "What percentage of MIT undergraduates have Math as their primary major? (Both XVIII and XVIII-C count.)",
    answer: 7.6075,
    geoguessr: null,
    scoringMethod: "percent",
    categories: ["major"],
  },
  {
    id: 9,
    text: "How many external windows are there in the Green Building?",
    answer: 324,
    geoguessr: null,
    scoringMethod: "10double",
    categories: ["green", "windows"],
  },
  {
    id: 10,
    text: "How many scientist names are there in Killian Court?",
    answer: 115,
    geoguessr: null,
    scoringMethod: "3double",
    categories: [],
  },
  {
    id: 11,
    text: "Where is this location on campus?",
    answer: 0,
    geoguessr: 3,
    scoringMethod: "raw",
    categories: [],
  },
  {
    id: 12,
    text: "How many non-overlapping Great Domes could you fit onto Briggs and O’Brien Fields?  Assume that the domes must lie on the ground in the normal dome orientation.",
    answer: 55,
    geoguessr: null,
    scoringMethod: "2double",
    categories: ["area"],
  },
  {
    id: 13,
    text: "By the time this quiz show ends, how many puzzles will your team have solved?",
    answer: 0,
    geoguessr: null,
    scoringMethod: "team_puzzle_solves",
    categories: ["meta"],
  },
  {
    id: 14,
    text: "In building 6C, there is a piece of artwork called Bars of Color within Squares. How many colored regions are there in that art?",
    answer: 133,
    geoguessr: null,
    scoringMethod: "4double",
    categories: ["art"],
  },
  {
    id: 15,
    text: "How many buildings on the MIT campus have building numbers that have no letters and are prime numbers?",
    answer: 11,
    geoguessr: null,
    scoringMethod: "12345",
    categories: ["buildings"],
  },
  {
    id: 16,
    text: "Where is this location on campus?",
    answer: 0,
    geoguessr: 4,
    scoringMethod: "raw",
    categories: [],
  },
  {
    id: 17,
    text: "How many letters are in the inscription on the third floor of Lobby 7?",
    answer: 116,
    geoguessr: null,
    scoringMethod: "3double",
    categories: [],
  },
  {
    id: 18,
    text: "How many official clubs / organizations have ASA-assigned bulletin board spaces on the Infinite Corridor?",
    answer: 84,
    geoguessr: null,
    scoringMethod: "3double",
    categories: [],
  },
  {
    id: 19,
    text: "Where is this location on campus?",
    answer: 0,
    geoguessr: 5,
    scoringMethod: "raw",
    categories: [],
  },
  {
    id: 20,
    text: "How many official Duck Konundra have there been in Mystery Hunt history?",
    answer: 8,
    geoguessr: null,
    scoringMethod: "12345",
    categories: ["hunt_history"],
  },
  {
    id: 21,
    text: "How many steps would you need to ascend in order to climb the Green Building 25 times?",
    answer: 10525,
    geoguessr: null,
    scoringMethod: "percent",
    categories: ["green"],
  },
  {
    id: 22,
    text: "How many varsity sports are offered at MIT? (Men’s/women’s/coed sports are all counted separately.)",
    answer: 33,
    geoguessr: null,
    scoringMethod: "1double",
    categories: ["sports"],
  },
  {
    id: 23,
    text: "Where is this location on campus?",
    answer: 0,
    geoguessr: 6,
    scoringMethod: "raw",
    categories: [],
  },
  {
    id: 24,
    text: "Assuming all registered teams were 100% accurate when they signed up, how many hunters are participating in this Mystery Hunt?",
    answer: 4164,
    geoguessr: null,
    scoringMethod: "percent",
    categories: ["hunt_current"],
  },
  {
    id: 25,
    text: "How many windows are there on the outside of Stata?",
    answer: 555,
    geoguessr: null,
    scoringMethod: "percent",
    categories: ["stata", "windows"],
  },
  {
    id: 26,
    text: "Where is this location on campus?",
    answer: 0,
    geoguessr: 7,
    scoringMethod: "raw",
    categories: [],
  },
  {
    id: 27,
    text: "By the time this quiz show ends, how many answer submissions (whether correct or not) will ALL participating teams have submitted for this Mystery Hunt?",
    answer: 0,
    geoguessr: null,
    scoringMethod: "all_submissions",
    categories: ["meta"],
  },
  {
    id: 28,
    text: "How many Nobel prizes are held by current MIT faculty and staff?",
    answer: 13,
    geoguessr: null,
    scoringMethod: "12468",
    categories: [],
  },
  {
    id: 29,
    text: "If you traveled from MIT Medical to building 7 through the basements using the shortest path, how far would you travel in smoots?",
    answer: 435,
    geoguessr: null,
    scoringMethod: "percent",
    categories: ["distance"],
  },
  {
    id: 30,
    text: "Where is this location on campus?",
    answer: 0,
    geoguessr: 8,
    scoringMethod: "raw",
    categories: [],
  },
  {
    id: 31,
    text: "How many distinct Greek letters are represented by MIT’s FSILGs?",
    answer: 18,
    geoguessr: null,
    scoringMethod: "12345",
    categories: [],
  },
  {
    id: 32,
    text: "How many bathrooms are there in the Main Group? (That’s buildings 1, 3, 5, 7, 2, 4, 6, 8, 6C, 10, and 11.)",
    answer: 65,
    geoguessr: null,
    scoringMethod: "2double",
    categories: ["bathrooms"],
  },
  {
    id: 33,
    text: "How many names are on the memorials in Lobby 10?",
    answer: 394,
    geoguessr: null,
    scoringMethod: "percent",
    categories: [],
  },
  {
    id: 34,
    text: "As of October 2023, how many professors were employed at MIT?",
    answer: 1089,
    geoguessr: null,
    scoringMethod: "percent",
    categories: [],
  },
  {
    id: 35,
    text: "Kresge Auditorium is shaped like an eighth of a sphere. What is the radius of that sphere, in smoots?",
    answer: 20.06,
    geoguessr: null,
    scoringMethod: "percent",
    categories: ["distance"],
  },
  {
    id: 36,
    text: "Ignoring wind resistance, what is the maximum speed (in miles per hour) that a pumpkin dropped from the top of the Green Building will reach?",
    answer: 91.03,
    geoguessr: null,
    scoringMethod: "percent",
    categories: ["green"],
  },
  {
    id: 37,
    text: "During MIThenge, what is the sun’s azimuthal angle, in degrees?",
    answer: 245.75,
    geoguessr: null,
    scoringMethod: "percent",
    categories: [],
  },
  {
    id: 38,
    text: "What percentage of MIT undergraduates have their primary major listed as literature, music, or theater arts?",
    answer: 0.11025358,
    geoguessr: null,
    scoringMethod: "percent",
    categories: ["majors"],
  },
  {
    id: 39,
    text: "How many differently-numbered MIT buildings are west of Mass Ave? (Buildings that have different letters, like W53A and W53 or W15 and WW15, count separately.)",
    answer: 74,
    geoguessr: null,
    scoringMethod: "2double",
    categories: ["buildings"],
  },
  {
    id: 40,
    text: "How many events were on the schedule for REX 2024?",
    answer: 303,
    geoguessr: null,
    scoringMethod: "9double",
    categories: [],
  },
  {
    id: 41,
    text: "How many different e-mail addresses are subscribed to ec-discuss?",
    answer: 1003,
    geoguessr: null,
    scoringMethod: "percent",
    categories: [],
  },
  {
    id: 42,
    text: "What percentage of applicants for the class of 2029 were accepted early?",
    answer: 5.981913,
    geoguessr: null,
    scoringMethod: "percent",
    categories: [],
  },
  {
    id: 43,
    text: "What is the complete dining capacity of Lobdell dining hall, including both balconies?",
    answer: 360,
    geoguessr: null,
    scoringMethod: "percent",
    categories: ["buildings"],
  },
  {
    id: 44,
    text: "How many trees are located within Killian Court?",
    answer: 64,
    geoguessr: null,
    scoringMethod: "2double",
    categories: [],
  },
  {
    id: 45,
    text: "Assuming ideal hexagonal packing density, how many standard orchestral snare drums could fit in one layer on the Kresge main stage?",
    answer: 1084,
    geoguessr: null,
    scoringMethod: "percent",
    categories: ["area"],
  },
  {
    id: 46,
    text: "How many truck loads did the MIT Museum need in order to move the collection to their new location?",
    answer: 135,
    geoguessr: null,
    scoringMethod: "4double",
    categories: [],
  },
  {
    id: 47,
    text: "Where is this location on campus?",
    answer: 0,
    geoguessr: 9,
    scoringMethod: "raw",
    categories: [],
  },
  {
    id: 48,
    text: "Where is this location on campus?",
    answer: 0,
    geoguessr: 10,
    scoringMethod: "raw",
    categories: [],
  },
  {
    id: 49,
    text: "Where is this location on campus?",
    answer: 0,
    geoguessr: 11,
    scoringMethod: "raw",
    categories: [],
  },
  {
    id: 50,
    text: "Where is this location on campus?",
    answer: 0,
    geoguessr: 12,
    scoringMethod: "raw",
    categories: [],
  },
  {
    id: 51,
    text: "Where is this location on campus?",
    answer: 0,
    geoguessr: 13,
    scoringMethod: "raw",
    categories: [],
  },
  {
    id: 52,
    text: "Where is this location on campus?",
    answer: 0,
    geoguessr: 14,
    scoringMethod: "raw",
    categories: [],
  },
  {
    id: 53,
    text: "Where is this location on campus?",
    answer: 0,
    geoguessr: 15,
    scoringMethod: "raw",
    categories: [],
  },
  {
    id: 54,
    text: "Where is this location on campus?",
    answer: 0,
    geoguessr: 16,
    scoringMethod: "raw",
    categories: [],
  },
];
