steps:
- name: gcr.io/$PROJECT_ID/nix-cache
  script: |
    nix-fast-build -f .#apps.x86_64-linux.apply.program --option extra-substituters s3://$_CACHE_BUCKET?endpoint=https://storage.googleapis.com --option require-sigs false --no-nom --skip-cached --copy-to s3://$_CACHE_BUCKET?endpoint=https://storage.googleapis.com
availableSecrets: 
  secretManager:
  - versionName: $_AWS_ACCESS_KEY_ID_SECRET
    env: AWS_ACCESS_KEY_ID
  - versionName: $_AWS_SECRET_ACCESS_KEY_SECRET
    env: AWS_SECRET_ACCESS_KEY
logsBucket: $_LOGS_BUCKET
