name: Lints
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./site
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up node
      uses: actions/setup-node@v4
      with:
        node-version: ">=22.0.0"
        cache: npm
        cache-dependency-path: site/package-lock.json
    - name: Install dependencies
      run: npm ci
    - name: Build the application (needed for site/dist/)
      run: npm run build
    - name: Run linters (tsc, prettier, eslint)
      run: npm run check
