name: Playwright Tests
on:
  push:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - uses: DeterminateSystems/flake-checker-action@main
    - name: Run playwright
      id: playwright
      run: |
        echo "::group::Build VM"
        out=$( (nix build --no-link --print-out-paths .#hunt2025-vm-test -L 3>&2 2>&1 1>&3- | sed 's/^vm-test-run-[^>]*> //') 3>&2 2>&1 1>&3- )
        echo "out=$out" >> $GITHUB_OUTPUT
        exit $(cat $out/status)
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: ${{ steps.playwright.outputs.out }}/playwright-report/
        retention-days: 30
